### ISSUE TITLE
Failed to start Zeppelin server when installing package via the installer because of wrong ZEPPELIN_NOTEBOOK_STORAGE value

### ISSUE THREAD

**Issue by mikaelfs** [NFLabs/z-manager#1]
Hi, 

I tried to install Zeppelin using the installer. Installation was conducted with the default option. The package bundle was downloaded and extracted successfully. However, when I ran Zeppelin via bin/zeppelin-daemon.sh the server could not be started.

Looking at one of the log files, which is ZEPPELIN_INSTALL_DIR/logs/zeppelin-$username-$hostname.$cluster.out, I found the following exception:

---

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.cxf.jaxrs.servlet.CXFNonSpringJaxrsServlet.createSingletonInstance(CXFNonSpringJaxrsServlet.java:382)
        at org.apache.cxf.jaxrs.servlet.CXFNonSpringJaxrsServlet.createApplicationInstance(CXFNonSpringJaxrsServlet.java:454)
        at org.apache.cxf.jaxrs.servlet.CXFNonSpringJaxrsServlet.createServerFromApplication(CXFNonSpringJaxrsServlet.java:432)
        at org.apache.cxf.jaxrs.servlet.CXFNonSpringJaxrsServlet.init(CXFNonSpringJaxrsServlet.java:93)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
        at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
        at org.eclipse.jetty.server.Server.doStart(Server.java:282)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.apache.zeppelin.server.ZeppelinServer.main(ZeppelinServer.java:107)
Caused by: java.lang.ClassNotFoundException: com.nflabs.zeppelinhub.notebook.repo.ZeppelinHubRepo
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:191)
        at org.apache.zeppelin.server.ZeppelinServer.<init>(ZeppelinServer.java:308)
##         ... 22 more

Line 308 of ZeppelinServer contains this code:
Class<?> notebookStorageClass = getClass().forName(
        conf.getString(ConfVars.ZEPPELIN_NOTEBOOK_STORAGE));

The default value in the ZeppelinConfiguration is VFSNotebookRepo instead of ZeppelinHubRepo. However, I noticed that in conf/zeppelin-env.sh, the value was assigned to "com.nflabs.zeppelinhub.notebook.repo.ZeppelinHubRepo".

In the current installer script, there is a procedure to download zeppelin-env.sh if it does not exist in the system. Intuitively, this error may have been caused by the preset value of ZEPPELIN_NOTEBOOK_STORAGE in the downloaded zeppelin-env.sh, but feel free to clarify if my assumption is incorrect.

**Comment by bzz** [comment]
@mikaelfs thanks for short notice! 
We have just pushed to fix and to get your instance of zeppelin working just delete three vars from `zeppelin-env.sh` - `ZEPPELIN_NOTEBOOK_STORAGE` and next two wth api address and token.

Let me know if that helps!
